### PR TITLE
Updating ndingest and the isntall script

### PR DESCRIPTION
**Pull request by Aeusman**

### CODE REVIEW

**Comment by Aeusman** [comment]
@kunallillaney This updates the ndingest submodule and the setup script to run the fake s3. 

Do we want to make this an optional thing that gets skipped on production server setup?

**Comment by kunallillaney** [comment]
@Aeusman Yeah let's make this optional for now. So turn it off by default and only run it for ndio. We will rectify this when kdevel is merged in.

**Comment by Aeusman** [comment]
Changed so any script with a production flag will not include the Redis/FakeS3

**Comment by Aeusman** [comment]
Ready to pull whenever!

**Pull request merged**
