### PR TITLE
Added raw GET endpoint to REST data service

### PR DESCRIPTION
**Pull request by tmbo**
I have added an endpoint to request data in a binary format which can easily be access in a programming language independent manner (e.g. it is quite challenging to access data in javascript that is using npz / blosc / hdf5 / jpeg).

This and #273 are quite important for us and it would be great if we can integrate them soon.

### CODE REVIEW

**Comment by kunallillaney** [comment]
@tmbo I need tests for the 'raw' service you have added. Have a look at test/test_blosc.py for a sample.

**Comment by tmbo** [comment]
Sure, will do. Unfortunately, I can't run any tests at the moment since I always get 
```
E           DoesNotExist: User matching query does not exist.
```
Is there any script / instruction on how to setup the db for testing?

**Comment by kunallillaney** [comment]
All of them are in the install script [here](https://github.com/neurodata/ndstore/blob/microns/setup/ndstore_install.sh). You need to create a database, django models and a superuser. Some of the services are celery jobs which require additional setup of supervisor and rabbit-mq. the install script assumes a clean Ubuntu 14.04 node and installs the entire stack on the node.

**Comment by tmbo** [comment]
Great, thanks for the hint. I added a test for the GET raw cube service. Let me know if there is anything else that needs fixing.

**Pull request merged**
